export const routes = {
  home: '/',
  // Public
  about: '/a-propos',
  president: '/mot-du-president',
  bureau: '/bureau-executif',
  conseil: '/conseil-des-sages',
  antennes: '/antennes',
  commissions: '/commissions',
  activities: '/activites',
  gallery: '/galerie',
  news: '/actualites',
  adhesion: '/adhesion',
  donate: '/don',
  contact: '/contact',
  // Legal
  legal: '/mentions-legales',
  privacy: '/confidentialite',
  cookies: '/cookies',
  terms: '/conditions',
  // Auth
  login: '/auth/login',
  register: '/auth/register',
  // Member portal
  member:           '/member/dashboard',
  memberCarte:      '/member/carte',
  memberProfil:     '/member/profil',
  memberActivites:  '/member/activites',
  memberMessages:   '/member/messages',
  // Admin portal
  admin:            '/admin/dashboard',
  adminAdherents:   '/admin/adherents',
  adminNouveau:     '/admin/adherents/nouveau',
  adminCartes:      '/admin/cartes',
  adminActivites:   '/admin/activites',
  adminGalerie:     '/admin/galerie',
  adminActualites:  '/admin/actualites',
  adminParametres:  '/admin/parametres',
  // Demo
  demo: '/demo',
  demoActivities: '/demo/activites',
  demoGallery: '/demo/galerie',
  demoMember: '/demo/member',
  demoAdmin: '/demo/admin',
} as const;
